name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Очень важно! Подтягивает submodule с GTest
    
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
      
    - name: Configure CMake with tests
      run: cmake -H. -B_build -DBUILD_TESTS=ON
      
    - name: Build
      run: cmake --build _build
      
    - name: Run tests (via CTest)
      run: cmake --build _build --target test -- ARGS=--verbose
      
    - name: Run test binary directly
      run: ./_build/check
